/* SimpleApp.scala */
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions._

object Q1 {
  def main(args: Array[String]) {
    val inputDir = args(0)
    var outputDir= args(1)
    val spark = SparkSession.builder.appName("Simple Application").getOrCreate()
	
	val schemaSource = new StructType ()
  .add(sourceId integerType(19, 0) NOT NULL)
  .add(scienceCcdExposureId integerType(19, 0) DEFAULT NULL)
  .add(filterId integerType(3, 0) NOT NULL)
  .add(objectId integerType(19, 0) DEFAULT NULL)
  .add(movingObjectId integerType(19, 0) DEFAULT NULL)
  .add(procHistoryId integerType(10, 0) NOT NULL)
  .add(ra floatType (24) NOT NULL)
  .add(raSigmaForDetection floatType DEFAULT NULL)
  .add(raSigmaForWcs floatType NOT NULL)
  .add(decl floatType (24) NOT NULL)
  .add(declSigmaForDetection floatType DEFAULT NULL)
  .add(declSigmaForWcs floatType NOT NULL)
  .add(htmId20 integerType(19, 0) NOT NULL)
  .add(xFlux floatType (24) DEFAULT NULL)
  .add(xFluxSigma floatType DEFAULT NULL)
  .add(yFlux floatType (24) DEFAULT NULL)
  .add(yFluxSigma floatType DEFAULT NULL)
  .add(raFlux floatType (24) DEFAULT NULL)
  .add(raFluxSigma floatType DEFAULT NULL)
  .add(declFlux floatType (24) DEFAULT NULL)
  .add(declFluxSigma floatType DEFAULT NULL)
  .add(xPeak floatType (24) DEFAULT NULL)
  .add(yPeak floatType (24) DEFAULT NULL)
  .add(raPeak floatType (24) DEFAULT NULL)
  .add(declPeak floatType (24) DEFAULT NULL)
  .add(xAstrom floatType (24) DEFAULT NULL)
  .add(xAstromSigma floatType DEFAULT NULL)
  .add(yAstrom floatType (24) DEFAULT NULL)
  .add(yAstromSigma floatType DEFAULT NULL)
  .add(raAstrom floatType (24) DEFAULT NULL)
  .add(raAstromSigma floatType DEFAULT NULL)
  .add(declAstrom floatType (24) DEFAULT NULL)
  .add(declAstromSigma floatType DEFAULT NULL)
  .add(raObject floatType (24) DEFAULT NULL)
  .add(declObject floatType (24) DEFAULT NULL)
  .add(taiMidPoint floatType (24) NOT NULL)
  .add(taiRange floatType DEFAULT NULL)
  .add(psfFlux floatType (24) DEFAULT NULL)
  .add(psfFluxSigma floatType DEFAULT NULL)
  .add(apFlux floatType (24) DEFAULT NULL)
  .add(apFluxSigma floatType DEFAULT NULL)
  .add(modelFlux floatType (24) DEFAULT NULL)
  .add(modelFluxSigma floatType DEFAULT NULL)
  .add(petroFlux floatType (24) DEFAULT NULL)
  .add(petroFluxSigma floatType DEFAULT NULL)
  .add(instFlux floatType (24) DEFAULT NULL)
  .add(instFluxSigma floatType DEFAULT NULL)
  .add(nonGrayCorrFlux floatType (24) DEFAULT NULL)
  .add(nonGrayCorrFluxSigma floatType DEFAULT NULL)
  .add(atmCorrFlux floatType (24) DEFAULT NULL)
  .add(atmCorrFluxSigma floatType DEFAULT NULL)
  .add(apDia floatType DEFAULT NULL)
  .add(Ixx floatType DEFAULT NULL)
  .add(IxxSigma floatType DEFAULT NULL)
  .add(Iyy floatType DEFAULT NULL)
  .add(IyySigma floatType DEFAULT NULL)
  .add(Ixy floatType DEFAULT NULL)
  .add(IxySigma floatType DEFAULT NULL)
  .add(psfIxx floatType DEFAULT NULL)
  .add(psfIxxSigma floatType DEFAULT NULL)
  .add(psfIyy floatType DEFAULT NULL)
  .add(psfIyySigma floatType DEFAULT NULL)
  .add(psfIxy floatType DEFAULT NULL)
  .add(psfIxySigma floatType DEFAULT NULL)
  .add(e1_SG floatType DEFAULT NULL)
  .add(e1_SG_Sigma floatType DEFAULT NULL)
  .add(e2_SG floatType DEFAULT NULL)
  .add(e2_SG_Sigma floatType DEFAULT NULL)
  .add(resolution_SG floatType DEFAULT NULL)
  .add(shear1_SG floatType DEFAULT NULL)
  .add(shear1_SG_Sigma floatType DEFAULT NULL)
  .add(shear2_SG floatType DEFAULT NULL)
  .add(shear2_SG_Sigma floatType DEFAULT NULL)
  .add(sourceWidth_SG floatType DEFAULT NULL)
  .add(sourceWidth_SG_Sigma floatType DEFAULT NULL)
  .add(shapeFlag_SG integerType(5, 0) DEFAULT NULL)
  .add(snr floatType NOT NULL)
  .add(chi2 floatType NOT NULL)
  .add(sky floatType DEFAULT NULL)
  .add(skySigma floatType DEFAULT NULL)
  .add(extendedness integerType(5, 0) DEFAULT NULL)
  .add(flux_Gaussian floatType (24) DEFAULT NULL)
  .add(flux_Gaussian_Sigma floatType DEFAULT NULL)
  .add(flux_ESG floatType (24) DEFAULT NULL)
  .add(flux_ESG_Sigma floatType DEFAULT NULL)
  .add(sersicN_SG floatType DEFAULT NULL)
  .add(sersicN_SG_Sigma floatType DEFAULT NULL)
  .add(radius_SG floatType DEFAULT NULL)
  .add(radius_SG_Sigma floatType DEFAULT NULL)
  .add(flux_flux_SG_Cov floatType DEFAULT NULL)
  .add(flux_e1_SG_Cov floatType DEFAULT NULL)
  .add(flux_e2_SG_Cov floatType DEFAULT NULL)
  .add(flux_radius_SG_Cov floatType DEFAULT NULL)
  .add(flux_sersicN_SG_Cov floatType DEFAULT NULL)
  .add(e1_e1_SG_Cov floatType DEFAULT NULL)
  .add(e1_e2_SG_Cov floatType DEFAULT NULL)
  .add(e1_radius_SG_Cov floatType DEFAULT NULL)
  .add(e1_sersicN_SG_Cov floatType DEFAULT NULL)
  .add(e2_e2_SG_Cov floatType DEFAULT NULL)
  .add(e2_radius_SG_Cov floatType DEFAULT NULL)
  .add(e2_sersicN_SG_Cov floatType DEFAULT NULL)
  .add(radius_radius_SG_Cov floatType DEFAULT NULL)
  .add(radius_sersicN_SG_Cov floatType DEFAULT NULL)
  .add(sersicN_sersicN_SG_Cov floatType DEFAULT NULL)
  .add(flagForAssociation integerType(5, 0) DEFAULT NULL)
  .add(flagForDetection integerType(19, 0) DEFAULT NULL)
  .add(flagForWcs integerType(5, 0) DEFAULT NULL  
);

	
	
	
    val collisions =spark
    .read
    .option("inferSchema","true").option("header","true")
    .csv(inputDir)
import spark.implicits._
    val donneesDF=collisions.expr("id").show()
    
    donneesDF.write
    .option("header",true)
    .option("sep",";")
    .csv(outputDir)
    spark.stop()
  }
}